### PR TITLE
Fixed/Updated: package.json

### PR DESCRIPTION
**Pull request by matthewjamesr**
## Fixed:

**npm install**: Generated error concerning invalid JSON. **Status**: fixed

## Updated:

**package.json**: Updated dependencies to reflect master version.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Oh... sorry. I'm an idiot. The `master` version of `package.json` I sent you was for Cachet itself. For this version all you need to do is remove that trailing comma I mentioned.

**Comment by GrahamCampbell** [comment]
We need to indent with 4 spaces, not 2.

**Comment by jbrooksuk** [comment]
Can you squash into one commit please :)

**Comment by matthewjamesr** [comment]
Should I just close PR and reopen?

**Comment by jbrooksuk** [comment]
Nope, squashing is easy. Do it in a rebase :)

**Comment by matthewjamesr** [comment]
Ahh! Cool one second :D

**Comment by GrahamCampbell** [comment]
I'm confused. You haven't actually changed anything now. You've just broken the indentation.

**Comment by jbrooksuk** [comment]
@GrahamCampbell there is a trailing comma at the moment.

**Comment by GrahamCampbell** [comment]
Sorted: https://github.com/cachethq/cachethq.io/commit/b5422101b475e8ea2e5b67e96d20341f2fb3cbd4.

**Comment by jbrooksuk** [comment]
Or do that haha.

**Comment by matthewjamesr** [comment]
Thanks @GrahamCampbell

**Comment by GrahamCampbell** [comment]
:D

**Pull request closed without merging**
