### PR TITLE
Link navbar logo

### PR DESCRIPTION
**Pull request by JayBizzle**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you merge this into `L5` please?

**Comment by JayBizzle** [comment]
???

**Comment by jbrooksuk** [comment]
Can you make this change on the `L5` branch instead please? :)

**Comment by JayBizzle** [comment]
I can't see a `L5` branch, just `master` :/

**Comment by GrahamCampbell** [comment]
@jbrooksuk lol. Wrong rep in your mind there...

**Comment by jbrooksuk** [comment]
Doh! Thanks @GrahamCampbell

**Comment by jbrooksuk** [comment]
Sorry @JayBizzle :)

**Pull request merged**
