### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
lol, your github username is confusing.

**Comment by jbrooksuk** [comment]
I keep doing that, even though I know it's **Cohen**. Sorry buddy.

**Comment by joecohens** [comment]
I know! Lol.. The thing it's that my name is so common it was imposible to get usernames so I appended an 's', like joe cohen's haha.

**Comment by GrahamCampbell** [comment]
you should have done joecohenlad. :P

**Comment by jbrooksuk** [comment]
@GrahamCampbell I read that as "gwan, lad". #gangster.

**Comment by joecohens** [comment]
LOL! I've tried so many.

**Comment by GrahamCampbell** [comment]
avs6 1

**Comment by joecohens** [comment]
And didn't want to use a number, I mean in twitter there until joecohen24 haha.

**Pull request merged**
