### PR TITLE
Fix typo on home page

### PR DESCRIPTION
**Pull request by lukerandall**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What? "prosperity" is correct.

**Comment by GrahamCampbell** [comment]
Hmm, d'no. Both kind of work, lol.

**Comment by GrahamCampbell** [comment]
@jbrooksuk What word did you want here?

**Comment by jbrooksuk** [comment]
Thanks @lukerandall I'm actually unsure of this change. http://public.wsu.edu/~brians/errors/prosperity.html

**Comment by jbrooksuk** [comment]
It makes sense.

**Pull request merged**
